### ISSUE TITLE
Epic: Evento Ethereum Dominicana Marzo - Nounish meetup

### ISSUE THREAD

**Issue by eenti** [ethdominicana/Coordination#7]
**Descripción**
Recibimos un grant de Nouns Amigos para realizar un meetup pequeño hablando sobre Nouns https://prop.house/nouns-amigos/reuniones-a-la-nounish/3539, ahora toca planificarlo.

**To-do**
- [ ] @efraeb #8 
- [ ] @eenti #9 
- [ ] Merch @efraeb y @crisoog
    - [ ] Impresión de stickers
    - [ ] Tshirts y/o otro merch físico para asistentes 
- [ ] @eenti #10 
- [ ] Fotografías para uso posterior @evalir

**Documentos o enlaces relevantes**
Propuesta: https://prop.house/nouns-amigos/reuniones-a-la-nounish/3539
Lugar: https://goo.gl/maps/SRW4Uf2i2frU1DKZA
